#pragma once
#include <Windows.h>
#include "InputHandles.h"
#include <io.h>

#define MARGIN_OUTER 20

#define MARGIN_FIELDS_X 10
#define MARGIN_FIELDS_Y 10

#define POS_TARGET_PATH_X MARGIN_OUTER
#define POS_TARGET_PATH_Y MARGIN_OUTER
#define DIM_TARGET_PATH_HEIGHT 30
#define DIM_TARGET_PATH_WIDTH 670

#define POS_RESEARCH_BTN_X POS_TARGET_PATH_X + DIM_TARGET_PATH_WIDTH - 1
#define POS_RESEARCH_BTN_Y POS_TARGET_PATH_Y
#define DIM_RESEARCH_BTN_WIDTH 30 + 1
#define DIM_RESEARCH_BTN_HEIGHT 30

#define POS_CYPHER_BTN_X MARGIN_OUTER
#define POS_CYPHER_BTN_Y MARGIN_OUTER + DIM_TARGET_PATH_HEIGHT + MARGIN_FIELDS_Y
#define DIM_CYPHER_BTN_WIDTH 150
#define DIM_CYPHER_BTN_HEIGHT 30

#define POS_OPTIONS_RECT_X POS_CYPHER_BTN_X + DIM_CYPHER_BTN_WIDTH + MARGIN_FIELDS_X
#define POS_OPTIONS_RECT_Y POS_CYPHER_BTN_Y
#define DIM_OPTIONS_RECT_WIDTH DIM_TARGET_PATH_WIDTH + DIM_RESEARCH_BTN_HEIGHT - 1 - (DIM_CYPHER_BTN_WIDTH + MARGIN_FIELDS_X)
#define DIM_OPTIONS_RECT_HEIGHT 200

#define POS_OPTIONS_EVOLVING_CYPH_X
#define POS_OPTIONS_EVOLVING_CYPH_Y
#define DIM_OPTIONS_EVOLVING_CYPH_WIDTH
#define DIM_OPTIONS_EVOLVING_CYPH_HEIGHT

#define RGB_WHITE RGB(255, 255, 255)
#define RGB_GREY RGB(120, 120, 120)
#define RGB_DARK_GREY RGB(60, 60, 60)
#define RGB_BLACK RGB(0, 0, 0)

int paint(HWND hwnd, HDC hdc, PAINTSTRUCT ps);